export { default as getTextData } from './temp.getTextData'
export { default as getTextAcount } from './temp.getTextAcount'
export { default as getTextQuiz } from './getTextQuiz'
export { default as getTextQuizSolve } from './temp.getTextQuizSolve'
export { default as getTextList } from './temp.getTextList'
export { default as getDiary } from './temp.getDiary'
export { default as getDiaryList } from './temp.getDiaryList'
