export { default as getTextData } from './temp.getTextData'
export { default as getTextAcount } from './temp.getTextAcount'
export { default as getTextQuiz } from './temp.getTextQuiz'
export { default as getTextQuizSolve } from './temp.getTextQuizSolve'
export { default as getTextList } from './temp.getTextList'
