name: Build & Push Arabugi Frontend Image

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/build_frontend_image.yaml
      - frontend/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop

    # Docker Hub 로그인 (보안 강화)
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Docker 이미지 빌드 (캐시 적용)
    - name: Build Docker Image
      run: |
        docker build --build-arg DB_HOST=${{ secrets.BACKEND_ADDRESS }} \
                     --tag ${{ secrets.DOCKER_REPO }}:frontend-${{ github.sha }} ./frontend

    # Docker 이미지 태깅 (latest 태그 추가)
    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_REPO }}:frontend-${{ github.sha }} ${{ secrets.DOCKER_REPO }}:frontend-latest

    # Docker Hub로 이미지 푸시
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_REPO }}:frontend-${{ github.sha }}
        docker push ${{ secrets.DOCKER_REPO }}:frontend-latest
