name: Build & Deploy Arabugi Realtime-FastAPI Image

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/build_realtime-fastapi_image.yaml
      - ai/realtime_fastapi/app.py
      - ai/realtime_fastapi/api/**
      - ai/realtime_fastapi/schemas/**
      - ai/realtime_fastapi/services/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      # Docker Hub 로그인 (보안 강화)
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Docker 이미지 빌드 (캐시 적용)
      - name: Build Docker Image
        run: |
          docker build --build-arg CLOVASTUDIO_API_KEY=${{ secrets.NAVER_API_KEY }} \
                       --tag ${{ secrets.DOCKER_REPO }}:realtime-fastapi-${{ github.sha }} ./ai/realtime_fastapi

      # Docker 이미지 태깅 (latest 태그 추가)
      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_REPO }}:realtime-fastapi-${{ github.sha }} ${{ secrets.DOCKER_REPO }}:realtime-fastapi-latest

      # Docker Hub로 이미지 푸시
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REPO }}:realtime-fastapi-${{ github.sha }}
          docker push ${{ secrets.DOCKER_REPO }}:realtime-fastapi-latest

deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: NCP login and pull & run docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AI_ADDRESS }}
        username: ${{ secrets.NCP_USERNAME }}
        password: ${{ secrets.AI_PASSWORD }}
        port: ${{ secrets.NCP_PORT }}
        script: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo docker stop arabugi-realtime-fastapi || true
          sudo docker rm -f arabugi-realtime-fastapi || true
          sudo docker rmi ${{ secrets.DOCKER_REPO }}:realtime-fastapi-latest || true
          sudo docker pull ${{ secrets.DOCKER_REPO }}:realtime-fastapi-latest
          docker run -d --name arabugi-realtime-fastapi -e TZ=Asia/Seoul -p 8001:8001 ${{ secrets.DOCKER_REPO }}:realtime-fastapi-latest
