name: Build & Deploy Arabugi Frontend Image

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/build_frontend_image.yaml
      - frontend/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop

    # Docker Hub 로그인 (보안 강화)
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Docker 이미지 빌드 (캐시 적용)
    - name: Build Docker Image
      run: |
        docker build --build-arg DB_HOST=${{ secrets.BACKEND_ADDRESS }} \
                     --tag ${{ secrets.DOCKER_REPO }}:frontend-${{ github.sha }} ./frontend

    # Docker 이미지 태깅 (latest 태그 추가)
    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_REPO }}:frontend-${{ github.sha }} ${{ secrets.DOCKER_REPO }}:frontend-latest

    # Docker Hub로 이미지 푸시
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_REPO }}:frontend-${{ github.sha }}
        docker push ${{ secrets.DOCKER_REPO }}:frontend-latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: NCP login and pull & run docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FRONTEND_ADDRESS }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.FRONTEND_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            sudo docker stop arabugi-frontend || true
            sudo docker rm -f arabugi-frontend || true
            sudo docker rmi ${{ secrets.DOCKER_REPO }}:frontend-latest || true
            sudo docker pull ${{ secrets.DOCKER_REPO }}:frontend-latest
            docker run -d --name arabugi-frontend -e TZ=Asia/Seoul -p 80:80 ${{ secrets.DOCKER_REPO }}:frontend-latest
