name: Build & Deploy Arabugi AI Batch-AirFlow Image

on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/build_batch-airflow_image.yaml
      - ai/batch_airflow/dags/**
      - ai/batch_airflow/prompt.json
      - ai/batch_airflow/run_scheduler_webserver.sh

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop

    # Docker Hub 로그인 (보안 강화)
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Docker 이미지 빌드 (캐시 적용)
    - name: Build Docker Image
      run: |
        docker build --build-arg NAVER_API_KEY=${{ secrets.NAVER_API_KEY }} \
                     --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                     --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                     --tag ${{ secrets.DOCKER_REPO }}:batch-airflow-${{ github.sha }} ./ai/batch_airflow

    # Docker 이미지 태깅 (latest 태그 추가)
    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_REPO }}:batch-airflow-${{ github.sha }} ${{ secrets.DOCKER_REPO }}:batch-airflow-latest

    # Docker Hub로 이미지 푸시
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_REPO }}:batch-airflow-${{ github.sha }}
        docker push ${{ secrets.DOCKER_REPO }}:batch-airflow-latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: NCP login and pull & run docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AI_ADDRESS }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.AI_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            sudo docker stop arabugi-batch-airflow || true
            sudo docker rm -f arabugi-batch-airflow || true
            sudo docker rmi ${{ secrets.DOCKER_REPO }}:batch-airflow-latest || true
            sudo docker pull ${{ secrets.DOCKER_REPO }}:batch-airflow-latest
            docker run -d --name arabugi-batch-airflow -e TZ=Asia/Seoul -p 8080:8080 ${{ secrets.DOCKER_REPO }}:batch-airflow-latest
